### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by upuil** [MeteoSwiss/c4dl-lightningdl#2]
Hi @jleinonen  I’m wondering  why my result is different with your results. [training.py](https://github.com/MeteoSwiss/c4dl-lightningdl/blob/master/scripts/training.py) is used to get `batch_gen`, and then used the functions in the [plots_lightning.py](https://github.com/MeteoSwiss/c4dl-lightningdl/blob/master/scripts/plots_lightning.py). Do you have any suggesions?  Would you mind give a reproduced jupyter notebook for your results? That would be great help. Thank you in advance.

[model-example-0.pdf](https://github.com/MeteoSwiss/c4dl-lightningdl/files/10081053/model-example-0.pdf)
[model-example-1.pdf](https://github.com/MeteoSwiss/c4dl-lightningdl/files/10081052/model-example-1.pdf)
[model-example-2.pdf](https://github.com/MeteoSwiss/c4dl-lightningdl/files/10081055/model-example-2.pdf)

**Comment by jleinonen** [comment]
Hi @upuil, thank for your comment again. It looks to me like you are getting the correct prediction but the plotting/scaling of the result is off somehow. Could you start by pasting the lines of code needed to reproduce this?

**Comment by upuil** [comment]
Thank you for your quick reply. @jleinonen I just simply invoke your functions with
```
file_dir = "../data/2020/"
batch_gen = setup_batch_gen(file_dir, file_suffix="2020", primary="RZC",
    target="occurrence-8-10", batch_size=48, epoch=datetime(1970,1,1))
ens_model, strategy = build_ensemble_model(batch_gen=batch_gen)
```
then plot all examples with 
`plot_all_examples(batch_gen = batch_gen, model = ens_model)`

**Comment by jleinonen** [comment]
Okay, this seems to be because you're not using the calibrated version of the model. The calibration shifts the model output so that it corresponds to the real probability of lightning occurrence.

First, you need the file [`c4dl-results-lightningdl.zip`](https://zenodo.org/record/6802292/files/c4dl-results-lightningdl.zip?download=1) from the data archive, if you don't have it yet. Below, I'll assume that you unzipped it to the `results` directory.

This should work, if you run it in the `scripts` directory:
```python
import training
import plots_lightning
from datetime import datetime
import numpy as np
from c4dl.analysis import calibration

# from your example
file_dir = "../data/2020/"
batch_gen = training.setup_batch_gen(file_dir, file_suffix="2020", primary="RZC",
    target="occurrence-8-10", batch_size=48, epoch=datetime(1970,1,1))
(ens_model, strategy) = build_ensemble_model(batch_gen=batch_gen)

# now let's load the calibration and create the calibrated_model wrapper
# the path below will depend on where you unzipped the file
occurrence = np.load("../results/lightning-study/valid/calibration-ensemble_dropout_weightdecay_noclassweight.npy")
nbins = len(occurrence)
p = np.linspace(0,1,nbins+1)
p = 0.5 * (p[:-1] + p[1:])
calib_model = calibration.calibrated_model(ens_model, p, occurrence)

# now plot with the calibrated model
plots_lightning.plot_all_examples(batch_gen=batch_gen, model=calib_model)
```

Sorry that this process is not very obvious or straightforward... let me know if this works on your system. If it does, I'll put it in the readme or in a notebook.

**Comment by upuil** [comment]
It works, thank you for your time and consideration.
